# Generated by Django 4.2.6 on 2023-10-07 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='routes',
            old_name='latitude',
            new_name='Dlatitude',
        ),
        migrations.RenameField(
            model_name='routes',
            old_name='longitude',
            new_name='Dlongitude',
        ),
        migrations.AddField(
            model_name='routes',
            name='Olatitude',
            field=models.DecimalField(decimal_places=20, default=1.0, max_digits=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='routes',
            name='Olongitude',
            field=models.DecimalField(decimal_places=20, default=1.0, max_digits=100),
            preserve_default=False,
        ),
    ]
